package com.wifi.pager

/**
 * R - Auto-generated resource IDs (simplified for build)
 * In actual Android project, this is generated by gradle
 */
object R {
    object layout {
        const val activity_main = android.R.layout.simple_list_item_1
    }

    object drawable {
        const val ic_notification = android.R.drawable.ic_dialog_info
    }

    object string {
        const val app_name = 0x7F050001
    }
}
